# 1. Use the node:19.7.0-alpine base image
FROM node:19.7.0-alpine

# 2. Set the environment variable NODE_ENV to production
ENV NODE_ENV=production

# 3. Create a new directory in root called labone
RUN mkdir /labone \
    # 3a. Change the ownership to the node user and node group
    && chown -R node:node /labone

# 3b. Set the working directory to the new folder
WORKDIR /labone

# 4. Set the user to node
USER node

# 5. Copy all source files to the container and change ownership to node user and group
COPY --chown=node:node . .

# 6. Run npm install to install Node.js packages
RUN npm install

# 7. Expose port 3000 for the app
EXPOSE 3000

# 8. Set the default command to run the Node.js application
CMD ["node", "src/index.js"]
